-- AlterTable
ALTER TABLE "TeamGame" ALTER COLUMN "FG3_PCT" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "FG_PCT" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "FT_PCT" SET DATA TYPE DOUBLE PRECISION;
